### ISSUE TITLE
[Question] Testing best practices

### ISSUE THREAD

**Issue by alexjlennard** [codeBelt/react-redux-architecture#30]
Could you possibly write a test for one of your actions that we could use as a guide? I am new to javascript/testing and am having trouble with the effects not being able to import environment module.

**Comment by codeBelt** [comment]
Ok I wrote some tests. Here are the commits/pr if you want to see what I did. I should of put all the commits into one pr.

- https://github.com/codeBelt/react-redux-architecture/pull/31/files
- https://github.com/codeBelt/react-redux-architecture/commit/76126663950d072845683e3da606ee38c88d5742
- https://github.com/codeBelt/react-redux-architecture/commit/8335af84b3265a7522e5beb877b755bf793996cb

**Comment by alexjlennard** [comment]
You rock. Thank you so so much.
